name: InvActions
version: '${version}'
main: me.xpyex.plugin.invactions.bukkit.InvActions
authors: [ XPYEX ]
api-version: 1.13
softdepend:
  - XPLib
commands:
  InvActions:
    aliases:
      - SortItems
