name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Fix file permissions
        run: |
          chmod +x gradlew
          git config --global core.fileMode true

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.9

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        continue-on-error: true

      - name: Build with Gradle Wrapper
        run: ./gradlew :ShadowAllVer:shadowJar --stacktrace

      - name: Verify build output
        run: ls -l ShadowAllVer/build/libs/

      - name: Get Version
        id: version
        run: |
          APP_VERSION=$(./gradlew properties -q | grep "version:" | awk '{print $2}')
          echo "VERSION=$APP_VERSION" >> $GITHUB_OUTPUT

      - name: Cleanup artifacts
        run: rm -f dependency-graph_*.json

      - name: Upload with Version
        uses: actions/upload-artifact@v4
        with:
          name: InvActions-${{ steps.version.outputs.VERSION }}-all.jar
          path: ShadowAllVer/build/libs/*.jar

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Fix file permissions
        run: chmod +x gradlew

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.9

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          arguments: --rerun-tasks
          dependency-graph-path: .github/dependency-graph/